### ISSUE TITLE
change text color in tab next to current

### ISSUE THREAD

**Issue by olegmedoed** [vmchale/ion-vim#3] opened 2017-09-14 21:31 UTC
When I have several tabs open and one of them is `foo.ion` script, a color of strings in other tabs becomes the same as in `foo.ion` script too. For example, in `bar.js` strings usually has tomato color, but if I open another tab with `foo.ion`, strings become white+bold.

**Comment by mwgkgk** [comment] 2018-08-09 15:04
The syntax file contains highlighting commands:
```
hi Operator    cterm=bold ctermfg=white
hi Array       cterm=bold ctermfg=lightblue
hi String      cterm=bold ctermfg=lightmagenta
hi DoubleQuote ctermfg=green
hi SingleQuote ctermfg=lightgreen
hi Numbers     ctermfg=cyan
hi! Comment    ctermfg=grey cterm=italic
hi Keywords    ctermfg=magenta cterm=bold
hi Flag cterm=bold ctermfg=darkyellow
```

This conflicts with user-set colorschemes.

**Comment by vmchale** [comment] 2018-08-09 15:16
Hi @mwgkgk. I've pushed a fix to this. Thanks for figuring this out!

**Comment by mwgkgk** [comment] 2018-08-09 15:46
Hey! The problem is that the syntax file is linking to a mix of locally defined and overridden highlight groups:
```vim
hi def link ionKeyword Keywords
hi def link ionArrayVar Array
hi def link variable String
hi def link ionNumber Numbers
hi def link ionDoubleQuote DoubleQuote
hi def link ionSingleQuote SingleQuote
hi def link ionProcess PreProc
hi def link ionComment Comment
hi def link ionOperator Operator
hi def link ionFlag Flag
```
So what @olegmedoed noticed was the default String group being overridden by
```vim
hi String      cterm=bold ctermfg=lightmagenta
```
The groups `DoubleQuote`, `SingleQuote`, `Flag`, `Number*s*`, `Keyword*s*`, and `Array` do not exist by default and thus will not be affected by any colorschemes that are not aware of them.

The groups `Operator`, `Comment`, `PreProc`, `String` do exist and thus hardcoded colors conflict with user-set colorschemes across all languages.

The solution would be to redesign the colorscheme using the default groups and remove any hardcoded colors.

**Closed** 2018-10-18 21:47 UTC
